import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../styles/globals.css'
import { Providers } from '@/providers/providers'
import { Toaster } from '@/components/ui/sonner'
import { Header } from '@/components/header'
import { getSession } from '@/lib/auth/manage-session'
import { cn } from '@/lib/utils'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await getSession()
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          {session && <Header />}
          <main
            className={cn({
              'pt-8 mb-8': session,
            })}
          >
            {children}
          </main>
          <Toaster />
        </Providers>
      </body>
    </html>
  )
}
