version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: "psyfi_mongodb"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=docker
      - MONGO_INITDB_ROOT_PASSWORD=docker
    ports:
      - "27017:27017"
    volumes:
      - psyfi_mongodb_data:/data/db
  postgres:
    container_name: psyfi_pg
    image: bitnami/postgresql:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: psyfi
    volumes:
      - psyfi_pg_data:/bitnami/
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
  keycloak:
    container_name: psyfi_keycloak
    image: bitnami/keycloak
    ports:
      - 8080:8080
      - 8443:8443
    environment:
      KEYCLOAK_ADMIN: docker
      KEYCLOAK_ADMIN_PASSWORD: docker
      KEYCLOAK_DATABASE_VENDOR: postgresql
      KEYCLOAK_DATABASE_HOST: postgres
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_USER: docker
      KEYCLOAK_DATABASE_NAME: psyfi
      KEYCLOAK_DATABASE_PASSWORD: docker
      KEYCLOAK_DATABASE_SCHEMA: auth
    depends_on:
      - postgres

volumes:
  psyfi_pg_data:
  psyfi_mongodb_data:
